Repository Eagle2gle/wealth-marble-backend, pull requests merged in 2023-02, with the labels that each got.

#65 fix/#41 JWT Token 저장 로직 및 결과 반환 변경
  .gitignore
  api/src/main/java/io/eagle/config/SecurityConfig.java
  api/src/main/java/io/eagle/domain/user/dto/CreateUserDto.java
  api/src/main/java/io/eagle/domain/user/mapper/UserRequestMapper.java
  api/src/main/java/io/eagle/domain/user/repository/UserRepository.java
  api/src/main/java/io/eagle/security/jwt/JwtRequestFilter.java
  api/src/main/java/io/eagle/security/jwt/JwtTokenProvider.java
  api/src/main/java/io/eagle/security/oauth/CustomOAuth2UserService.java
  api/src/main/java/io/eagle/security/oauth/OAuth2SuccessHandler.java
Labels: 🐞 bug

#66 Feat/#48 해당 유저의 관심상품 목록 전체 다 가져오는 API
  api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
  api/src/main/java/io/eagle/domain/interest/dto/InterestDto.java
  api/src/main/java/io/eagle/domain/interest/dto/InterestInfoDto.java
  api/src/main/java/io/eagle/domain/interest/repository/InterestRepository.java
  api/src/main/java/io/eagle/domain/interest/repository/InterestRepositoryCustom.java
  api/src/main/java/io/eagle/domain/interest/repository/InterestRepositoryImpl.java
  api/src/main/java/io/eagle/domain/interest/service/InterestService.java
Labels: 🌟 feature

#69 Feat/#68 interest register and delete API
  api/src/main/java/io/eagle/config/SecurityConfig.java
  api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
  api/src/main/java/io/eagle/domain/interest/dto/InterestDto.java
  api/src/main/java/io/eagle/domain/interest/repository/InterestRepositoryCustom.java
  api/src/main/java/io/eagle/domain/interest/repository/InterestRepositoryImpl.java
  api/src/main/java/io/eagle/domain/interest/service/InterestService.java
  core/src/main/java/io/eagle/entity/Interest.java
Labels: 🌟 feature

#74 Feat/#73 PriceInfo 기본세팅
  api/src/main/java/io/eagle/domain/PriceInfo/controller/PriceInfoController.java
  api/src/main/java/io/eagle/domain/PriceInfo/repository/PriceInfoRepository.java
  api/src/main/java/io/eagle/domain/PriceInfo/repository/PriceInfoRepositoryCustom.java
  api/src/main/java/io/eagle/domain/PriceInfo/repository/PriceInfoRepositoryImpl.java
  api/src/main/java/io/eagle/domain/PriceInfo/service/PriceInfoService.java
  core/src/main/java/io/eagle/entity/PriceInfo.java
Labels: 🌟 feature

#76 Feat/#75 마켓에서 차트 데이터를 가져오는 API
  .gitignore
  api/src/main/java/io/eagle/common/QueryStringArgResolver.java
  api/src/main/java/io/eagle/config/SecurityConfig.java
  api/src/main/java/io/eagle/domain/PriceInfo/controller/PriceInfoController.java
  api/src/main/java/io/eagle/domain/PriceInfo/dto/ChartRequestDto.java
  api/src/main/java/io/eagle/domain/PriceInfo/dto/ChartResponseDto.java
  api/src/main/java/io/eagle/domain/PriceInfo/dto/ChartTotalDto.java
  api/src/main/java/io/eagle/domain/PriceInfo/repository/PriceInfoRepositoryCustom.java
  api/src/main/java/io/eagle/domain/PriceInfo/repository/PriceInfoRepositoryImpl.java
  api/src/main/java/io/eagle/domain/PriceInfo/service/PriceInfoService.java
  api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
  api/src/main/java/io/eagle/domain/transaction/controller/TransactionController.java
  api/src/main/java/io/eagle/domain/vacation/controller/MarketController.java
  api/src/main/java/io/eagle/domain/vacation/dto/CreateCahootsDto.java
  api/src/main/java/io/eagle/domain/vacation/dto/MarketDetailDto.java
  api/src/main/java/io/eagle/domain/vacation/repository/VacationCustomImpl.java
  api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
  api/src/test/java/io/eagle/config/TestConfig.java
  api/src/test/java/io/eagle/domain/PriceInfo/repository/PriceInfoRepositoryTest.java
  build.gradle
  core/src/main/java/io/eagle/entity/Interest.java
  core/src/main/java/io/eagle/entity/Vacation.java
Labels: 🌟 feature

#79 refactor/#78 security를 공통 설정으로 변경
  api/src/main/java/io/eagle/domain/interest/service/InterestService.java
  api/src/main/java/io/eagle/domain/transaction/service/TransactionService.java
  api/src/main/java/io/eagle/domain/user/service/UserService.java
  api/src/test/java/io/eagle/domain/PriceInfo/repository/PriceInfoRepositoryTest.java
  core/src/main/java/io/eagle/config/SecurityConfig.java
  core/src/main/java/io/eagle/repository/UserRepository.java
  core/src/main/java/io/eagle/repository/UserRepositoryCustom.java
  core/src/main/java/io/eagle/repository/UserRepositoryImpl.java
  core/src/main/java/io/eagle/security/dto/CreateUserDto.java
  core/src/main/java/io/eagle/security/jwt/JwtRequestFilter.java
  core/src/main/java/io/eagle/security/jwt/JwtTokenProvider.java
  core/src/main/java/io/eagle/security/mapper/UserRequestMapper.java
  core/src/main/java/io/eagle/security/oauth/CustomOAuth2UserService.java
  core/src/main/java/io/eagle/security/oauth/OAuth2SuccessHandler.java
  core/src/main/java/io/eagle/security/oauth/OAuthAttributes.java
Labels: 🔨 Refactor

#81 Feat/#80 특정 휴양지의 거래 내역을 페이지 별로 가져오기
  api/src/main/java/io/eagle/domain/transaction/controller/TransactionController.java
  api/src/main/java/io/eagle/domain/transaction/dto/TransactionRequestDto.java
  api/src/main/java/io/eagle/domain/transaction/dto/TransactionResponseDto.java
  api/src/main/java/io/eagle/domain/transaction/repository/TransactionRepository.java
  api/src/main/java/io/eagle/domain/transaction/repository/TransactionRepositoryCustom.java
  api/src/main/java/io/eagle/domain/transaction/repository/TransactionRepositoryImpl.java
  api/src/main/java/io/eagle/domain/transaction/service/TransactionService.java
  api/src/test/java/io/eagle/common/TestUtil.java
  api/src/test/java/io/eagle/domain/transaction/repository/TransactionRepositoryTest.java
  core/src/main/java/io/eagle/config/QueryDslConfig.java
  core/src/main/java/io/eagle/entity/Transaction.java
Labels: 🌟 feature

#84 Feat/#83 마켓 정보에서 휴양지 상세 정보 가져오기
  api/src/main/java/io/eagle/domain/vacation/controller/MarketController.java
  api/src/main/java/io/eagle/domain/vacation/dto/response/MarketDetailDto.java
  api/src/main/java/io/eagle/domain/vacation/dto/response/MarketInfoDto.java
  api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
  api/src/test/java/io/eagle/domain/vacation/service/MarketServiceTest.java
Labels: 🌟 feature

#87 refactor/#86 AuthService 분리를 통한 결합도 수준 줄이기
  api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
  api/src/main/java/io/eagle/domain/interest/service/InterestService.java
  api/src/main/java/io/eagle/domain/user/service/UserService.java
  core/src/main/java/io/eagle/auth/AuthDetails.java
  core/src/main/java/io/eagle/auth/AuthService.java
  core/src/main/java/io/eagle/entity/User.java
  core/src/main/java/io/eagle/security/jwt/JwtRequestFilter.java
  core/src/main/java/io/eagle/security/jwt/JwtTokenProvider.java
  core/src/main/java/io/eagle/security/oauth/CustomOAuth2UserService.java
  core/src/main/java/io/eagle/security/oauth/OAuth2SuccessHandler.java
Labels: 🔨 Refactor

#91 Chore/#90 기본적인 Batch Job 환경 세팅
  batch/src/main/java/io/eagle/BatchApplication.java
  batch/src/main/java/io/eagle/Main.java
  batch/src/main/java/io/eagle/job/VacationJobConfiguration.java
  batch/src/main/resources/application.yml
Labels: 🛠️ setting

#96 Hotfix: socket dockerizing 시 kafka 연결 설정을 위한 환경변수 설정
  socket/Dockerfile
  socket/src/main/java/io/eagle/common/KafkaConstants.java
  socket/src/main/java/io/eagle/domain/order/dto/request/MessageDto.java
  socket/src/main/resources/application.yml
  socket/src/test/java/io/eagle/domain/order/service/OrderServiceTest.java
Labels: 🐞 bug

#93 Feat/#92 User Interest에 pagination 적용
  api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
  api/src/main/java/io/eagle/domain/interest/repository/InterestRepositoryCustom.java
  api/src/main/java/io/eagle/domain/interest/repository/InterestRepositoryImpl.java
  api/src/main/java/io/eagle/domain/interest/service/InterestService.java
  api/src/test/java/io/eagle/common/TestUtil.java
  api/src/test/java/io/eagle/domain/interest/repository/InterestRepositoryTest.java
  core/src/main/java/io/eagle/entity/Interest.java
Labels: 🌟 feature

#95 Feat/#94 무한스크롤용 휴양지 목록 가져오기
  api/src/main/java/io/eagle/domain/vacation/controller/MarketController.java
  api/src/main/java/io/eagle/domain/vacation/dto/response/MarketListDto.java
  api/src/main/java/io/eagle/domain/vacation/repository/VacationCustom.java
  api/src/main/java/io/eagle/domain/vacation/repository/VacationCustomImpl.java
  api/src/main/java/io/eagle/domain/vacation/repository/VacationRepository.java
  api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
  api/src/test/java/io/eagle/domain/vacation/service/MarketServiceTest.java
  core/src/main/java/io/eagle/entity/Vacation.java
  core/src/main/java/io/eagle/entity/type/PriceStatus.java
  core/src/main/java/io/eagle/entity/type/VacationStatusType.java
Labels: 🌟 feature

#112 Feat/#111 휴양지 Batch 시스템 도입
  batch/src/main/java/io/eagle/BatchApplication.java
  batch/src/main/java/io/eagle/chunk/processor/OrderTransitionProcessor.java
  batch/src/main/java/io/eagle/chunk/processor/TransactionAssignProcessor.java
  batch/src/main/java/io/eagle/chunk/processor/VacationTransitionProcessor.java
  batch/src/main/java/io/eagle/chunk/writer/OrderTransitionItemWriter.java
  batch/src/main/java/io/eagle/chunk/writer/TransactionAssignItemWriter.java
  batch/src/main/java/io/eagle/domain/order/vo/OrderHistoryVO.java
  batch/src/main/java/io/eagle/job/VacationJobConfiguration.java
  batch/src/main/java/io/eagle/listener/CustomJobExecutionListener.java
  batch/src/main/java/io/eagle/listener/CustomStepExecutionListener.java
  batch/src/main/java/io/eagle/rowmapper/OrderHistoryVORowMapper.java
  batch/src/main/java/io/eagle/rowmapper/VacationMapper.java
  batch/src/main/java/io/eagle/scheduler/JobRunner.java
  batch/src/main/java/io/eagle/scheduler/VacationJobRunner.java
  batch/src/main/java/io/eagle/scheduler/VacationSchJob.java
  build.gradle
  core/src/main/java/io/eagle/entity/Order.java
  core/src/main/java/io/eagle/entity/Transaction.java
  core/src/main/java/io/eagle/entity/Vacation.java
  core/src/main/java/io/eagle/entity/type/OrderStatus.java
Labels: 🌟 feature

#114 Feat/#113 Stock 테이블 생성 및 Batch Process 개선
  batch/src/main/java/io/eagle/chunk/processor/CreateStockProcessor.java
  batch/src/main/java/io/eagle/chunk/processor/OrderTransitionProcessor.java
  batch/src/main/java/io/eagle/chunk/processor/RetrieveMoneyProcessor.java
  batch/src/main/java/io/eagle/chunk/processor/TransactionAssignProcessor.java
  batch/src/main/java/io/eagle/chunk/processor/VacationTransitionProcessor.java
  batch/src/main/java/io/eagle/chunk/writer/CreateStockItemWriter.java
  batch/src/main/java/io/eagle/chunk/writer/DeleteContestParticipationItemWriter.java
  batch/src/main/java/io/eagle/chunk/writer/OrderTransitionItemWriter.java
  batch/src/main/java/io/eagle/chunk/writer/RetrieveMoneyWriter.java
  batch/src/main/java/io/eagle/chunk/writer/TransactionAssignItemWriter.java
  batch/src/main/java/io/eagle/domain/OrderHistoryVO.java
  batch/src/main/java/io/eagle/domain/RetrieveMoneyVO.java
  batch/src/main/java/io/eagle/job/VacationJobConfiguration.java
  batch/src/main/java/io/eagle/listener/CustomJobExecutionListener.java
  batch/src/main/java/io/eagle/listener/CustomStepExecutionListener.java
  batch/src/main/java/io/eagle/rowmapper/OrderHistoryVORowMapper.java
  core/src/main/java/io/eagle/entity/ContestParticipation.java
  core/src/main/java/io/eagle/entity/Stock.java
  core/src/main/java/io/eagle/entity/User.java
  core/src/main/java/io/eagle/entity/type/ContestParticipationStatus.java
Labels: 🌟 feature

#116 Fix/#115 API 연동 시 발생하는 Error 수정
  api/src/main/java/io/eagle/domain/ContestParticipation/service/ContestParticipationService.java
  api/src/main/java/io/eagle/domain/PriceInfo/controller/PriceInfoController.java
  api/src/main/java/io/eagle/domain/PriceInfo/service/PriceInfoService.java
  api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
  api/src/main/java/io/eagle/domain/interest/repository/InterestRepositoryImpl.java
  api/src/main/java/io/eagle/domain/interest/service/InterestService.java
  api/src/test/java/io/eagle/domain/vacation/service/CahootsServiceTest.java
  core/src/main/java/io/eagle/auth/AuthDetails.java
  core/src/main/java/io/eagle/auth/AuthService.java
  core/src/main/java/io/eagle/config/SecurityConfig.java
  core/src/main/java/io/eagle/entity/Interest.java
  core/src/main/java/io/eagle/entity/Picture.java
  core/src/main/java/io/eagle/security/jwt/JwtTokenProvider.java
Labels: 🐞 bug

#119 Feat/#118 관심상품 필터링 기능 구현하기
  api/src/main/java/io/eagle/domain/interest/controller/InterestController.java
  api/src/main/java/io/eagle/domain/interest/dto/InterestDto.java
  api/src/main/java/io/eagle/domain/interest/service/InterestService.java
  api/src/test/java/io/eagle/common/TestUtil.java
  api/src/test/java/io/eagle/domain/interest/service/InterestServiceTest.java
Labels: 🌟 feature

#124 Feat/#43 내 정보 가져오기
  api/src/main/java/io/eagle/domain/stock/dto/StockInfoDto.java
  api/src/main/java/io/eagle/domain/stock/repository/StockRepository.java
  api/src/main/java/io/eagle/domain/stock/repository/StockRepositoryCustom.java
  api/src/main/java/io/eagle/domain/stock/repository/StockRepositoryImpl.java
  api/src/main/java/io/eagle/domain/user/controller/UserController.java
  api/src/main/java/io/eagle/domain/user/dto/response/UserInfoDto.java
  api/src/main/java/io/eagle/domain/user/service/UserService.java
  api/src/test/java/io/eagle/domain/user/service/UserServiceTest.java
Labels: 🌟 feature

#125 Feat/#45 참여한 공모 내역 전달하기
  api/src/main/java/io/eagle/domain/ContestParticipation/controller/ContestParticipationController.java
  api/src/main/java/io/eagle/domain/ContestParticipation/dto/response/ContestParticipationMineDto.java
  api/src/main/java/io/eagle/domain/ContestParticipation/repository/ContestParticipationRepositoryCustom.java
  api/src/main/java/io/eagle/domain/ContestParticipation/repository/ContestParticipationRepositoryImpl.java
  api/src/main/java/io/eagle/domain/ContestParticipation/service/ContestParticipationService.java
  api/src/main/java/io/eagle/domain/transaction/controller/TransactionController.java
  api/src/main/java/io/eagle/domain/transaction/dto/UserTransactionInfoDto.java
  api/src/main/java/io/eagle/domain/transaction/dto/request/TransactionRequestDto.java
  api/src/main/java/io/eagle/domain/transaction/dto/response/TransactionResponseDto.java
  api/src/main/java/io/eagle/domain/transaction/dto/response/UserTransactionInfoDto.java
  api/src/main/java/io/eagle/domain/transaction/repository/TransactionRepositoryCustom.java
  api/src/main/java/io/eagle/domain/transaction/repository/TransactionRepositoryImpl.java
  api/src/main/java/io/eagle/domain/transaction/service/TransactionService.java
  api/src/test/java/io/eagle/common/TestUtil.java
  api/src/test/java/io/eagle/domain/ContestParticipation/service/ContestParticipationServiceTest.java
  api/src/test/java/io/eagle/domain/transaction/repository/TransactionRepositoryTest.java
  core/src/main/java/io/eagle/entity/Transaction.java
Labels: 🌟 feature

#126 Feat/#47 내 자산현황 가져오기
  api/src/main/java/io/eagle/domain/stock/controller/StockController.java
  api/src/main/java/io/eagle/domain/stock/dto/response/StockMineDto.java
  api/src/main/java/io/eagle/domain/stock/repository/StockRepositoryCustom.java
  api/src/main/java/io/eagle/domain/stock/repository/StockRepositoryImpl.java
  api/src/main/java/io/eagle/domain/stock/service/StockService.java
  api/src/main/java/io/eagle/domain/stock/vo/StockMineVO.java
  api/src/test/java/io/eagle/common/TestUtil.java
  api/src/test/java/io/eagle/domain/stock/service/StockServiceTest.java
  build.gradle
Labels: 🌟 feature

#130 Feat/#129 market ranking 시스템 도입
  .github/workflows/API_CD.yml
  api/src/main/java/io/eagle/domain/vacation/controller/MarketController.java
  api/src/main/java/io/eagle/domain/vacation/dto/response/MarketRankDto.java
  api/src/main/java/io/eagle/domain/vacation/repository/VacationCustom.java
  api/src/main/java/io/eagle/domain/vacation/repository/VacationCustomImpl.java
  api/src/main/java/io/eagle/domain/vacation/service/MarketService.java
  api/src/main/java/io/eagle/domain/vacation/vo/MarketQueryVO.java
  core/src/main/java/io/eagle/config/RedisConfig.java
  core/src/main/java/io/eagle/entity/type/MarketRankingType.java
  core/src/main/resources/application-core.yml
  socket/src/main/java/io/eagle/domain/PriceInfo/repository/PriceInfoRepository.java
  socket/src/main/java/io/eagle/domain/order/service/OrderService.java
Labels: 🌟 feature

#134 Feat/#117 최근 거래내역 가져오기
  api/src/main/java/io/eagle/domain/PriceInfo/repository/PriceInfoRepository.java
  api/src/main/java/io/eagle/domain/transaction/controller/TransactionController.java
  api/src/main/java/io/eagle/domain/transaction/dto/request/RecentTransactionRequestDto.java
  api/src/main/java/io/eagle/domain/transaction/dto/response/RecentTransactionResponseDto.java
  api/src/main/java/io/eagle/domain/transaction/service/TransactionService.java
  api/src/test/java/io/eagle/common/TestUtil.java
  api/src/test/java/io/eagle/domain/transaction/service/TransactionServiceTest.java
  batch/src/main/java/io/eagle/common/BatchConstant.java
  batch/src/main/java/io/eagle/domain/RecentTransactionRequestVO.java
  batch/src/main/java/io/eagle/job/RecentTransactionJobConfiguration.java
  batch/src/main/java/io/eagle/scheduler/RecentJobRunner.java
  batch/src/main/java/io/eagle/scheduler/RecentSchJob.java
  batch/src/main/java/io/eagle/service/RecentTransactionApiService.java
  batch/src/main/java/io/eagle/tasklet/ReadTransactionTasklet.java
  batch/src/main/resources/application.yml
Labels: 🌟 feature
