Repository Eagle2gle/wealth-marble-backend, pull requests merged in 2023-01, with the labels that each got.

#21 bug: 환경변수 입력 수정
  .github/workflows/CD.yml
Labels: 🐞 bug

#35 merge : dev에서 feat/#25-user-basic 업데이트
  .github/workflows/CD.yml
  .gitignore
  build.gradle
  src/main/java/io/eagle/wealthmarblebackend/config/S3Config.java
  src/main/java/io/eagle/wealthmarblebackend/domain/ContestParticipation/controller/ContestParticipationController.java
  src/main/java/io/eagle/wealthmarblebackend/domain/ContestParticipation/dto/HistoryCahootsDto.java
  src/main/java/io/eagle/wealthmarblebackend/domain/ContestParticipation/dto/HistoryCahootsDtoList.java
  src/main/java/io/eagle/wealthmarblebackend/domain/ContestParticipation/entity/ContestParticipation.java
  src/main/java/io/eagle/wealthmarblebackend/domain/ContestParticipation/repository/ContestParticipationRepositoryCustom.java
  src/main/java/io/eagle/wealthmarblebackend/domain/ContestParticipation/repository/ContestParticipationRepositoryImpl.java
  src/main/java/io/eagle/wealthmarblebackend/domain/ContestParticipation/service/ContestParticipationService.java
  src/main/java/io/eagle/wealthmarblebackend/domain/picture/S3.java
  src/main/java/io/eagle/wealthmarblebackend/domain/picture/entity/Picture.java
  src/main/java/io/eagle/wealthmarblebackend/domain/picture/repository/PictureRepository.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/controller/CahootsController.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/dto/BreifCahootListDto.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/dto/BreifCahootsDto.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/dto/CreateCahootsDto.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/dto/DetailCahootsDto.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/dto/HistoryCahootsDto.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/entity/Vacation.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/entity/embeded/Period.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/entity/embeded/Plan.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/entity/embeded/Stock.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/entity/embeded/Theme.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/repository/VacationCustom.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/repository/VacationCustomImpl.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/repository/VacationRepository.java
  src/main/java/io/eagle/wealthmarblebackend/domain/vacation/service/CahootsService.java
  src/main/java/io/eagle/wealthmarblebackend/exception/GlobalExceptionHandler.java
  src/main/java/io/eagle/wealthmarblebackend/exception/S3Exception.java
  src/main/java/io/eagle/wealthmarblebackend/exception/error/ErrorCode.java
  src/main/resources/application.yml
  src/test/java/io/eagle/wealthmarblebackend/domain/vacation/service/CahootsServiceTest.java
Labels: enhancement

#36 Feat/#25 User JWT 토큰 발급 과정 생성
  build.gradle
  src/main/java/io/eagle/wealthmarblebackend/config/SecurityConfig.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/domain/User.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/entity/User.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/entity/type/ProviderType.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/entity/type/Rank.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/entity/type/Role.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/repository/UserRepository.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/service/UserService.java
  src/main/java/io/eagle/wealthmarblebackend/security/jwt/JwtRequestFilter.java
  src/main/java/io/eagle/wealthmarblebackend/security/jwt/JwtTokenProvider.java
Labels: 🌟 feature

#42 Feat/#41 구글 로그인 구현하기
  .github/workflows/CD.yml
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/io/eagle/wealthmarblebackend/WealthMarbleBackendApplication.java
  src/main/java/io/eagle/wealthmarblebackend/config/SecurityConfig.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/dto/CreateUserDto.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/entity/User.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/entity/type/Ranks.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/mapper/UserRequestMapper.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/repository/UserRepository.java
  src/main/java/io/eagle/wealthmarblebackend/security/jwt/JwtTokenProvider.java
  src/main/java/io/eagle/wealthmarblebackend/security/oauth/CustomOAuth2UserService.java
  src/main/java/io/eagle/wealthmarblebackend/security/oauth/OAuth2SuccessHandler.java
  src/main/java/io/eagle/wealthmarblebackend/security/oauth/OAuthAttributes.java
  src/main/resources/application.yml
Labels: 🌟 feature

#51 Feat/#11 basic entity 제작
  src/main/java/io/eagle/wealthmarblebackend/domain/interest/entity/Interest.java
  src/main/java/io/eagle/wealthmarblebackend/domain/interest/repository/InterestRepository.java
  src/main/java/io/eagle/wealthmarblebackend/domain/interest/repository/InterestRepositoryCustom.java
  src/main/java/io/eagle/wealthmarblebackend/domain/interest/repository/InterestRepositoryImpl.java
  src/main/java/io/eagle/wealthmarblebackend/domain/order/entity/Order.java
  src/main/java/io/eagle/wealthmarblebackend/domain/order/entity/type/OrderStatus.java
  src/main/java/io/eagle/wealthmarblebackend/domain/order/entity/type/OrderType.java
  src/main/java/io/eagle/wealthmarblebackend/domain/order/repository/OrderRepository.java
  src/main/java/io/eagle/wealthmarblebackend/domain/order/repository/OrderRepositoryCustom.java
  src/main/java/io/eagle/wealthmarblebackend/domain/order/repository/OrderRepositoryImpl.java
  src/main/java/io/eagle/wealthmarblebackend/domain/transaction/dto/UserTransactionInfoDto.java
  src/main/java/io/eagle/wealthmarblebackend/domain/transaction/entity/Transaction.java
  src/main/java/io/eagle/wealthmarblebackend/domain/transaction/repository/TransactionRepository.java
  src/main/java/io/eagle/wealthmarblebackend/domain/transaction/repository/TransactionRepositoryCustom.java
  src/main/java/io/eagle/wealthmarblebackend/domain/transaction/repository/TransactionRepositoryImpl.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/repository/UserRepository.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/repository/UserRepositoryCustom.java
  src/main/java/io/eagle/wealthmarblebackend/domain/user/repository/UserRepositoryImpl.java
Labels: 🌟 feature

#52 Feat/#46 내가 참여한 transaction 정보 가져오기
  src/main/java/io/eagle/wealthmarblebackend/domain/transaction/controller/TransactionController.java
  src/main/java/io/eagle/wealthmarblebackend/domain/transaction/service/TransactionService.java
Labels: 🌟 feature
